// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "accel_in_circle_in_circle.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic accel_in_circle_in_circle::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic accel_in_circle_in_circle::ap_const_logic_0 = sc_dt::Log_0;
const bool accel_in_circle_in_circle::ap_const_boolean_1 = true;
const bool accel_in_circle_in_circle::ap_const_boolean_0 = false;
const sc_lv<32> accel_in_circle_in_circle::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> accel_in_circle_in_circle::ap_const_lv32_17 = "10111";
const sc_lv<32> accel_in_circle_in_circle::ap_const_lv32_1E = "11110";
const sc_lv<8> accel_in_circle_in_circle::ap_const_lv8_FF = "11111111";
const sc_lv<23> accel_in_circle_in_circle::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> accel_in_circle_in_circle::ap_const_lv5_2 = "10";

accel_in_circle_in_circle::accel_in_circle_in_circle(sc_module_name name) : sc_module(name), mVcdFile(0) {
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->din0(father_0_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->din1(innerdata_0_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->ce(grp_fu_78_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1->dout(grp_fu_78_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->din0(father_2_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->din1(innerdata_0_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->ce(grp_fu_84_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2->dout(grp_fu_84_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->din0(father_4_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->din1(innerdata_0_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->ce(grp_fu_90_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3->dout(grp_fu_90_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->din0(father_1_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->din1(innerdata_1_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->ce(grp_fu_96_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4->dout(grp_fu_96_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->din0(father_3_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->din1(innerdata_1_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->ce(grp_fu_102_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5->dout(grp_fu_102_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->din0(father_5_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->din1(innerdata_1_read_int_reg);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->ce(grp_fu_108_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6->dout(grp_fu_108_p2);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7 = new accel_in_circle_accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7");
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->clk(ap_clk);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->reset(ap_rst);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->din0(tmp_reg_344);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->din1(tmp_1_reg_349);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->ce(grp_fu_114_ce);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7->dout(grp_fu_114_p2);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8 = new accel_in_circle_accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8");
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->clk(ap_clk);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->reset(ap_rst);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->din0(tmp_2_reg_354);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->din1(tmp_3_reg_359);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->ce(grp_fu_118_ce);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8->dout(grp_fu_118_p2);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9 = new accel_in_circle_accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9");
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->clk(ap_clk);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->reset(ap_rst);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->din0(tmp_4_reg_364);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->din1(tmp_5_reg_369);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->ce(grp_fu_122_ce);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9->dout(grp_fu_122_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->din0(tmp_6_reg_374);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->din1(tmp_7_reg_379);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->ce(grp_fu_126_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10->dout(grp_fu_126_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->din0(tmp_8_reg_384);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->din1(tmp_9_reg_389);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->ce(grp_fu_130_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11->dout(grp_fu_130_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->din0(tmp_s_reg_394);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->din1(tmp_10_reg_399);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->ce(grp_fu_134_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12->dout(grp_fu_134_p2);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13 = new accel_in_circle_accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13");
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->clk(ap_clk);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->reset(ap_rst);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->din0(tmp_11_reg_434);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->din1(tmp_12_reg_439);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->ce(grp_fu_138_ce);
    accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13->dout(grp_fu_138_p2);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14 = new accel_in_circle_accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0<1,3,32,32,32>("accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14");
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->clk(ap_clk);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->reset(ap_rst);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->din0(tmp_13_reg_449);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->din1(tmp_14_reg_444_pp0_iter12_reg);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->ce(grp_fu_142_ce);
    accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14->dout(grp_fu_142_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->din0(xda_reg_296);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->din1(xda_reg_296);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->ce(grp_fu_146_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15->dout(grp_fu_146_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->din0(yda_reg_320);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->din1(yda_reg_320);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->ce(grp_fu_150_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16->dout(grp_fu_150_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->din0(xdb_reg_304);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->din1(xdb_reg_304);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->ce(grp_fu_154_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17->dout(grp_fu_154_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->din0(ydb_reg_328);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->din1(ydb_reg_328);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->ce(grp_fu_158_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18->dout(grp_fu_158_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->din0(xdc_reg_312);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->din1(xdc_reg_312);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->ce(grp_fu_162_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19->dout(grp_fu_162_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->din0(ydc_reg_336);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->din1(ydc_reg_336);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->ce(grp_fu_166_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20->dout(grp_fu_166_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->din0(xdb_reg_304);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->din1(ydc_reg_336);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->ce(grp_fu_170_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21->dout(grp_fu_170_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->din0(xdc_reg_312);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->din1(ydb_reg_328);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->ce(grp_fu_174_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22->dout(grp_fu_174_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->din0(xda_reg_296);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->din1(ydc_reg_336);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->ce(grp_fu_178_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23->dout(grp_fu_178_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->din0(xdc_reg_312);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->din1(yda_reg_320);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->ce(grp_fu_182_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24->dout(grp_fu_182_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->din0(xda_reg_296);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->din1(ydb_reg_328);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->ce(grp_fu_186_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25->dout(grp_fu_186_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->din0(xdb_reg_304);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->din1(yda_reg_320);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->ce(grp_fu_190_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26->dout(grp_fu_190_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->din0(da2da2_reg_404);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->din1(min1_reg_419);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->ce(grp_fu_194_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27->dout(grp_fu_194_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->din0(db2db2_reg_409);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->din1(min2_reg_424);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->ce(grp_fu_198_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28->dout(grp_fu_198_p2);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29 = new accel_in_circle_accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0<1,2,32,32,32>("accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29");
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->clk(ap_clk);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->reset(ap_rst);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->din0(dc2dc2_reg_414);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->din1(min3_reg_429);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->ce(grp_fu_202_ce);
    accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29->dout(grp_fu_202_p2);
    accel_in_circle_fcmp_32ns_32ns_1_1_0_U30 = new accel_in_circle_accel_in_circle_fcmp_32ns_32ns_1_1_0<1,1,32,32,1>("accel_in_circle_fcmp_32ns_32ns_1_1_0_U30");
    accel_in_circle_fcmp_32ns_32ns_1_1_0_U30->din0(det_reg_454);
    accel_in_circle_fcmp_32ns_32ns_1_1_0_U30->din1(ap_var_for_const0);
    accel_in_circle_fcmp_32ns_32ns_1_1_0_U30->opcode(ap_var_for_const1);
    accel_in_circle_fcmp_32ns_32ns_1_1_0_U30->dout(tmp_16_fu_206_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_and_ln30_fu_246_p2);
    sensitive << ( or_ln30_fu_240_p2 );
    sensitive << ( tmp_16_fu_206_p2 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_00001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_return);
    sensitive << ( and_ln30_fu_246_p2 );
    sensitive << ( ap_ce_reg );
    sensitive << ( ap_return_int_reg );

    SC_METHOD(thread_bitcast_ln30_fu_211_p1);
    sensitive << ( det_reg_454 );

    SC_METHOD(thread_grp_fu_102_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_108_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_114_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_118_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_122_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_126_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_130_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_134_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_138_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_142_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_146_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_150_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_154_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_158_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_162_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_166_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_170_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_174_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_178_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_182_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_186_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_190_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_194_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_198_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_202_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_78_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_84_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_90_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_grp_fu_96_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_icmp_ln30_1_fu_234_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( trunc_ln30_fu_224_p1 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_icmp_ln30_fu_228_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_15_fu_214_p4 );
    sensitive << ( ap_ce_reg );

    SC_METHOD(thread_or_ln30_fu_240_p2);
    sensitive << ( icmp_ln30_1_fu_234_p2 );
    sensitive << ( icmp_ln30_fu_228_p2 );

    SC_METHOD(thread_tmp_15_fu_214_p4);
    sensitive << ( bitcast_ln30_fu_211_p1 );

    SC_METHOD(thread_trunc_ln30_fu_224_p1);
    sensitive << ( bitcast_ln30_fu_211_p1 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "accel_in_circle_in_circle_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, innerdata_0_read, "(port)innerdata_0_read");
    sc_trace(mVcdFile, innerdata_1_read, "(port)innerdata_1_read");
    sc_trace(mVcdFile, father_0_read, "(port)father_0_read");
    sc_trace(mVcdFile, father_1_read, "(port)father_1_read");
    sc_trace(mVcdFile, father_2_read, "(port)father_2_read");
    sc_trace(mVcdFile, father_3_read, "(port)father_3_read");
    sc_trace(mVcdFile, father_4_read, "(port)father_4_read");
    sc_trace(mVcdFile, father_5_read, "(port)father_5_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11, "ap_block_state12_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12, "ap_block_state13_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13, "ap_block_state14_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14, "ap_block_state15_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15, "ap_block_state16_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16, "ap_block_state17_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, grp_fu_78_p2, "grp_fu_78_p2");
    sc_trace(mVcdFile, xda_reg_296, "xda_reg_296");
    sc_trace(mVcdFile, grp_fu_84_p2, "grp_fu_84_p2");
    sc_trace(mVcdFile, xdb_reg_304, "xdb_reg_304");
    sc_trace(mVcdFile, grp_fu_90_p2, "grp_fu_90_p2");
    sc_trace(mVcdFile, xdc_reg_312, "xdc_reg_312");
    sc_trace(mVcdFile, grp_fu_96_p2, "grp_fu_96_p2");
    sc_trace(mVcdFile, yda_reg_320, "yda_reg_320");
    sc_trace(mVcdFile, grp_fu_102_p2, "grp_fu_102_p2");
    sc_trace(mVcdFile, ydb_reg_328, "ydb_reg_328");
    sc_trace(mVcdFile, grp_fu_108_p2, "grp_fu_108_p2");
    sc_trace(mVcdFile, ydc_reg_336, "ydc_reg_336");
    sc_trace(mVcdFile, grp_fu_146_p2, "grp_fu_146_p2");
    sc_trace(mVcdFile, tmp_reg_344, "tmp_reg_344");
    sc_trace(mVcdFile, grp_fu_150_p2, "grp_fu_150_p2");
    sc_trace(mVcdFile, tmp_1_reg_349, "tmp_1_reg_349");
    sc_trace(mVcdFile, grp_fu_154_p2, "grp_fu_154_p2");
    sc_trace(mVcdFile, tmp_2_reg_354, "tmp_2_reg_354");
    sc_trace(mVcdFile, grp_fu_158_p2, "grp_fu_158_p2");
    sc_trace(mVcdFile, tmp_3_reg_359, "tmp_3_reg_359");
    sc_trace(mVcdFile, grp_fu_162_p2, "grp_fu_162_p2");
    sc_trace(mVcdFile, tmp_4_reg_364, "tmp_4_reg_364");
    sc_trace(mVcdFile, grp_fu_166_p2, "grp_fu_166_p2");
    sc_trace(mVcdFile, tmp_5_reg_369, "tmp_5_reg_369");
    sc_trace(mVcdFile, grp_fu_170_p2, "grp_fu_170_p2");
    sc_trace(mVcdFile, tmp_6_reg_374, "tmp_6_reg_374");
    sc_trace(mVcdFile, grp_fu_174_p2, "grp_fu_174_p2");
    sc_trace(mVcdFile, tmp_7_reg_379, "tmp_7_reg_379");
    sc_trace(mVcdFile, grp_fu_178_p2, "grp_fu_178_p2");
    sc_trace(mVcdFile, tmp_8_reg_384, "tmp_8_reg_384");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, tmp_9_reg_389, "tmp_9_reg_389");
    sc_trace(mVcdFile, grp_fu_186_p2, "grp_fu_186_p2");
    sc_trace(mVcdFile, tmp_s_reg_394, "tmp_s_reg_394");
    sc_trace(mVcdFile, grp_fu_190_p2, "grp_fu_190_p2");
    sc_trace(mVcdFile, tmp_10_reg_399, "tmp_10_reg_399");
    sc_trace(mVcdFile, grp_fu_114_p2, "grp_fu_114_p2");
    sc_trace(mVcdFile, da2da2_reg_404, "da2da2_reg_404");
    sc_trace(mVcdFile, grp_fu_118_p2, "grp_fu_118_p2");
    sc_trace(mVcdFile, db2db2_reg_409, "db2db2_reg_409");
    sc_trace(mVcdFile, grp_fu_122_p2, "grp_fu_122_p2");
    sc_trace(mVcdFile, dc2dc2_reg_414, "dc2dc2_reg_414");
    sc_trace(mVcdFile, grp_fu_126_p2, "grp_fu_126_p2");
    sc_trace(mVcdFile, min1_reg_419, "min1_reg_419");
    sc_trace(mVcdFile, grp_fu_130_p2, "grp_fu_130_p2");
    sc_trace(mVcdFile, min2_reg_424, "min2_reg_424");
    sc_trace(mVcdFile, grp_fu_134_p2, "grp_fu_134_p2");
    sc_trace(mVcdFile, min3_reg_429, "min3_reg_429");
    sc_trace(mVcdFile, grp_fu_194_p2, "grp_fu_194_p2");
    sc_trace(mVcdFile, tmp_11_reg_434, "tmp_11_reg_434");
    sc_trace(mVcdFile, grp_fu_198_p2, "grp_fu_198_p2");
    sc_trace(mVcdFile, tmp_12_reg_439, "tmp_12_reg_439");
    sc_trace(mVcdFile, grp_fu_202_p2, "grp_fu_202_p2");
    sc_trace(mVcdFile, tmp_14_reg_444, "tmp_14_reg_444");
    sc_trace(mVcdFile, tmp_14_reg_444_pp0_iter10_reg, "tmp_14_reg_444_pp0_iter10_reg");
    sc_trace(mVcdFile, tmp_14_reg_444_pp0_iter11_reg, "tmp_14_reg_444_pp0_iter11_reg");
    sc_trace(mVcdFile, tmp_14_reg_444_pp0_iter12_reg, "tmp_14_reg_444_pp0_iter12_reg");
    sc_trace(mVcdFile, grp_fu_138_p2, "grp_fu_138_p2");
    sc_trace(mVcdFile, tmp_13_reg_449, "tmp_13_reg_449");
    sc_trace(mVcdFile, grp_fu_142_p2, "grp_fu_142_p2");
    sc_trace(mVcdFile, det_reg_454, "det_reg_454");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, bitcast_ln30_fu_211_p1, "bitcast_ln30_fu_211_p1");
    sc_trace(mVcdFile, tmp_15_fu_214_p4, "tmp_15_fu_214_p4");
    sc_trace(mVcdFile, trunc_ln30_fu_224_p1, "trunc_ln30_fu_224_p1");
    sc_trace(mVcdFile, icmp_ln30_1_fu_234_p2, "icmp_ln30_1_fu_234_p2");
    sc_trace(mVcdFile, icmp_ln30_fu_228_p2, "icmp_ln30_fu_228_p2");
    sc_trace(mVcdFile, or_ln30_fu_240_p2, "or_ln30_fu_240_p2");
    sc_trace(mVcdFile, tmp_16_fu_206_p2, "tmp_16_fu_206_p2");
    sc_trace(mVcdFile, grp_fu_78_ce, "grp_fu_78_ce");
    sc_trace(mVcdFile, grp_fu_84_ce, "grp_fu_84_ce");
    sc_trace(mVcdFile, grp_fu_90_ce, "grp_fu_90_ce");
    sc_trace(mVcdFile, grp_fu_96_ce, "grp_fu_96_ce");
    sc_trace(mVcdFile, grp_fu_102_ce, "grp_fu_102_ce");
    sc_trace(mVcdFile, grp_fu_108_ce, "grp_fu_108_ce");
    sc_trace(mVcdFile, grp_fu_114_ce, "grp_fu_114_ce");
    sc_trace(mVcdFile, grp_fu_118_ce, "grp_fu_118_ce");
    sc_trace(mVcdFile, grp_fu_122_ce, "grp_fu_122_ce");
    sc_trace(mVcdFile, grp_fu_126_ce, "grp_fu_126_ce");
    sc_trace(mVcdFile, grp_fu_130_ce, "grp_fu_130_ce");
    sc_trace(mVcdFile, grp_fu_134_ce, "grp_fu_134_ce");
    sc_trace(mVcdFile, grp_fu_138_ce, "grp_fu_138_ce");
    sc_trace(mVcdFile, grp_fu_142_ce, "grp_fu_142_ce");
    sc_trace(mVcdFile, grp_fu_146_ce, "grp_fu_146_ce");
    sc_trace(mVcdFile, grp_fu_150_ce, "grp_fu_150_ce");
    sc_trace(mVcdFile, grp_fu_154_ce, "grp_fu_154_ce");
    sc_trace(mVcdFile, grp_fu_158_ce, "grp_fu_158_ce");
    sc_trace(mVcdFile, grp_fu_162_ce, "grp_fu_162_ce");
    sc_trace(mVcdFile, grp_fu_166_ce, "grp_fu_166_ce");
    sc_trace(mVcdFile, grp_fu_170_ce, "grp_fu_170_ce");
    sc_trace(mVcdFile, grp_fu_174_ce, "grp_fu_174_ce");
    sc_trace(mVcdFile, grp_fu_178_ce, "grp_fu_178_ce");
    sc_trace(mVcdFile, grp_fu_182_ce, "grp_fu_182_ce");
    sc_trace(mVcdFile, grp_fu_186_ce, "grp_fu_186_ce");
    sc_trace(mVcdFile, grp_fu_190_ce, "grp_fu_190_ce");
    sc_trace(mVcdFile, grp_fu_194_ce, "grp_fu_194_ce");
    sc_trace(mVcdFile, grp_fu_198_ce, "grp_fu_198_ce");
    sc_trace(mVcdFile, grp_fu_202_ce, "grp_fu_202_ce");
    sc_trace(mVcdFile, ap_block_pp0_stage0_00001, "ap_block_pp0_stage0_00001");
    sc_trace(mVcdFile, and_ln30_fu_246_p2, "and_ln30_fu_246_p2");
    sc_trace(mVcdFile, ap_ce_reg, "ap_ce_reg");
    sc_trace(mVcdFile, innerdata_0_read_int_reg, "innerdata_0_read_int_reg");
    sc_trace(mVcdFile, innerdata_1_read_int_reg, "innerdata_1_read_int_reg");
    sc_trace(mVcdFile, father_0_read_int_reg, "father_0_read_int_reg");
    sc_trace(mVcdFile, father_1_read_int_reg, "father_1_read_int_reg");
    sc_trace(mVcdFile, father_2_read_int_reg, "father_2_read_int_reg");
    sc_trace(mVcdFile, father_3_read_int_reg, "father_3_read_int_reg");
    sc_trace(mVcdFile, father_4_read_int_reg, "father_4_read_int_reg");
    sc_trace(mVcdFile, father_5_read_int_reg, "father_5_read_int_reg");
    sc_trace(mVcdFile, ap_return_int_reg, "ap_return_int_reg");
#endif

    }
}

accel_in_circle_in_circle::~accel_in_circle_in_circle() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U1;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U2;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U3;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U4;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U5;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U6;
    delete accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U7;
    delete accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U8;
    delete accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U9;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U10;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U11;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U12;
    delete accel_in_circle_fsub_32ns_32ns_32_3_full_dsp_0_U13;
    delete accel_in_circle_fadd_32ns_32ns_32_3_full_dsp_0_U14;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U15;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U16;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U17;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U18;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U19;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U20;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U21;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U22;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U23;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U24;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U25;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U26;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U27;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U28;
    delete accel_in_circle_fmul_32ns_32ns_32_2_max_dsp_0_U29;
    delete accel_in_circle_fcmp_32ns_32ns_1_1_0_U30;
}

void accel_in_circle_in_circle::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_0;
}

void accel_in_circle_in_circle::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void accel_in_circle_in_circle::thread_ap_clk_no_reset_() {
    ap_ce_reg = ap_ce.read();
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return_int_reg = and_ln30_fu_246_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce_reg.read(), ap_const_logic_1))) {
        da2da2_reg_404 = grp_fu_114_p2.read();
        db2db2_reg_409 = grp_fu_118_p2.read();
        dc2dc2_reg_414 = grp_fu_122_p2.read();
        det_reg_454 = grp_fu_142_p2.read();
        min1_reg_419 = grp_fu_126_p2.read();
        min2_reg_424 = grp_fu_130_p2.read();
        min3_reg_429 = grp_fu_134_p2.read();
        tmp_10_reg_399 = grp_fu_190_p2.read();
        tmp_11_reg_434 = grp_fu_194_p2.read();
        tmp_12_reg_439 = grp_fu_198_p2.read();
        tmp_13_reg_449 = grp_fu_138_p2.read();
        tmp_14_reg_444 = grp_fu_202_p2.read();
        tmp_14_reg_444_pp0_iter10_reg = tmp_14_reg_444.read();
        tmp_14_reg_444_pp0_iter11_reg = tmp_14_reg_444_pp0_iter10_reg.read();
        tmp_14_reg_444_pp0_iter12_reg = tmp_14_reg_444_pp0_iter11_reg.read();
        tmp_1_reg_349 = grp_fu_150_p2.read();
        tmp_2_reg_354 = grp_fu_154_p2.read();
        tmp_3_reg_359 = grp_fu_158_p2.read();
        tmp_4_reg_364 = grp_fu_162_p2.read();
        tmp_5_reg_369 = grp_fu_166_p2.read();
        tmp_6_reg_374 = grp_fu_170_p2.read();
        tmp_7_reg_379 = grp_fu_174_p2.read();
        tmp_8_reg_384 = grp_fu_178_p2.read();
        tmp_9_reg_389 = grp_fu_182_p2.read();
        tmp_reg_344 = grp_fu_146_p2.read();
        tmp_s_reg_394 = grp_fu_186_p2.read();
        xda_reg_296 = grp_fu_78_p2.read();
        xdb_reg_304 = grp_fu_84_p2.read();
        xdc_reg_312 = grp_fu_90_p2.read();
        yda_reg_320 = grp_fu_96_p2.read();
        ydb_reg_328 = grp_fu_102_p2.read();
        ydc_reg_336 = grp_fu_108_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read())) {
        father_0_read_int_reg = father_0_read.read();
        father_1_read_int_reg = father_1_read.read();
        father_2_read_int_reg = father_2_read.read();
        father_3_read_int_reg = father_3_read.read();
        father_4_read_int_reg = father_4_read.read();
        father_5_read_int_reg = father_5_read.read();
        innerdata_0_read_int_reg = innerdata_0_read.read();
        innerdata_1_read_int_reg = innerdata_1_read.read();
    }
}

void accel_in_circle_in_circle::thread_and_ln30_fu_246_p2() {
    and_ln30_fu_246_p2 = (or_ln30_fu_240_p2.read() & tmp_16_fu_206_p2.read());
}

void accel_in_circle_in_circle::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_pp0_stage0_00001() {
    ap_block_pp0_stage0_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state12_pp0_stage0_iter11() {
    ap_block_state12_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state13_pp0_stage0_iter12() {
    ap_block_state13_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state14_pp0_stage0_iter13() {
    ap_block_state14_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state15_pp0_stage0_iter14() {
    ap_block_state15_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state16_pp0_stage0_iter15() {
    ap_block_state16_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state17_pp0_stage0_iter16() {
    ap_block_state17_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void accel_in_circle_in_circle::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_ce_reg.read())) {
        ap_return = ap_return_int_reg.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read())) {
        ap_return = and_ln30_fu_246_p2.read();
    }
}

void accel_in_circle_in_circle::thread_bitcast_ln30_fu_211_p1() {
    bitcast_ln30_fu_211_p1 = det_reg_454.read();
}

void accel_in_circle_in_circle::thread_grp_fu_102_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_102_ce = ap_const_logic_1;
    } else {
        grp_fu_102_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_108_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_108_ce = ap_const_logic_1;
    } else {
        grp_fu_108_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_114_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_114_ce = ap_const_logic_1;
    } else {
        grp_fu_114_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_118_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_118_ce = ap_const_logic_1;
    } else {
        grp_fu_118_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_122_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_122_ce = ap_const_logic_1;
    } else {
        grp_fu_122_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_126_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_126_ce = ap_const_logic_1;
    } else {
        grp_fu_126_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_130_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_130_ce = ap_const_logic_1;
    } else {
        grp_fu_130_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_134_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_134_ce = ap_const_logic_1;
    } else {
        grp_fu_134_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_138_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_138_ce = ap_const_logic_1;
    } else {
        grp_fu_138_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_142_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_142_ce = ap_const_logic_1;
    } else {
        grp_fu_142_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_146_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_146_ce = ap_const_logic_1;
    } else {
        grp_fu_146_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_150_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_150_ce = ap_const_logic_1;
    } else {
        grp_fu_150_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_154_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_154_ce = ap_const_logic_1;
    } else {
        grp_fu_154_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_158_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_158_ce = ap_const_logic_1;
    } else {
        grp_fu_158_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_162_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_162_ce = ap_const_logic_1;
    } else {
        grp_fu_162_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_166_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_166_ce = ap_const_logic_1;
    } else {
        grp_fu_166_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_170_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_170_ce = ap_const_logic_1;
    } else {
        grp_fu_170_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_174_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_174_ce = ap_const_logic_1;
    } else {
        grp_fu_174_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_178_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_178_ce = ap_const_logic_1;
    } else {
        grp_fu_178_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_182_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_182_ce = ap_const_logic_1;
    } else {
        grp_fu_182_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_186_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_186_ce = ap_const_logic_1;
    } else {
        grp_fu_186_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_190_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_190_ce = ap_const_logic_1;
    } else {
        grp_fu_190_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_194_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_194_ce = ap_const_logic_1;
    } else {
        grp_fu_194_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_198_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_198_ce = ap_const_logic_1;
    } else {
        grp_fu_198_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_202_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_202_ce = ap_const_logic_1;
    } else {
        grp_fu_202_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_78_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_78_ce = ap_const_logic_1;
    } else {
        grp_fu_78_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_84_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_84_ce = ap_const_logic_1;
    } else {
        grp_fu_84_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_90_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_90_ce = ap_const_logic_1;
    } else {
        grp_fu_90_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_grp_fu_96_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce_reg.read()))) {
        grp_fu_96_ce = ap_const_logic_1;
    } else {
        grp_fu_96_ce = ap_const_logic_0;
    }
}

void accel_in_circle_in_circle::thread_icmp_ln30_1_fu_234_p2() {
    icmp_ln30_1_fu_234_p2 = (!trunc_ln30_fu_224_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln30_fu_224_p1.read() == ap_const_lv23_0);
}

void accel_in_circle_in_circle::thread_icmp_ln30_fu_228_p2() {
    icmp_ln30_fu_228_p2 = (!tmp_15_fu_214_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_15_fu_214_p4.read() != ap_const_lv8_FF);
}

void accel_in_circle_in_circle::thread_or_ln30_fu_240_p2() {
    or_ln30_fu_240_p2 = (icmp_ln30_1_fu_234_p2.read() | icmp_ln30_fu_228_p2.read());
}

void accel_in_circle_in_circle::thread_tmp_15_fu_214_p4() {
    tmp_15_fu_214_p4 = bitcast_ln30_fu_211_p1.read().range(30, 23);
}

void accel_in_circle_in_circle::thread_trunc_ln30_fu_224_p1() {
    trunc_ln30_fu_224_p1 = bitcast_ln30_fu_211_p1.read().range(23-1, 0);
}

}

