// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _in_circle_in_circle_HH_
#define _in_circle_in_circle_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "in_circle_in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1.h"
#include "in_circle_in_circle_fsub_32ns_32ns_32_2_full_dsp_1.h"
#include "in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1.h"
#include "in_circle_in_circle_fcmp_32ns_32ns_1_1_1.h"

namespace ap_rtl {

struct in_circle_in_circle : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > t_p1_id;
    sc_in< sc_lv<32> > t_p1_x;
    sc_in< sc_lv<32> > t_p1_y;
    sc_in< sc_lv<32> > t_p2_id;
    sc_in< sc_lv<32> > t_p2_x;
    sc_in< sc_lv<32> > t_p2_y;
    sc_in< sc_lv<32> > t_p3_id;
    sc_in< sc_lv<32> > t_p3_x;
    sc_in< sc_lv<32> > t_p3_y;
    sc_in< sc_lv<32> > d_id;
    sc_in< sc_lv<32> > d_x;
    sc_in< sc_lv<32> > d_y;
    sc_out< sc_lv<32> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    in_circle_in_circle(sc_module_name name);
    SC_HAS_PROCESS(in_circle_in_circle);

    ~in_circle_in_circle();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    in_circle_in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1_U1;
    in_circle_in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1_U2;
    in_circle_in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_faddfsub_32ns_32ns_32_2_full_dsp_1_U3;
    in_circle_in_circle_fsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_fsub_32ns_32ns_32_2_full_dsp_1_U4;
    in_circle_in_circle_fsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_fsub_32ns_32ns_32_2_full_dsp_1_U5;
    in_circle_in_circle_fsub_32ns_32ns_32_2_full_dsp_1<1,2,32,32,32>* in_circle_fsub_32ns_32ns_32_2_full_dsp_1_U6;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U7;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U8;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U9;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U10;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U11;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U12;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U13;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U14;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U15;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U16;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U17;
    in_circle_in_circle_fmul_32ns_32ns_32_2_max_dsp_1<1,2,32,32,32>* in_circle_fmul_32ns_32ns_32_2_max_dsp_1_U18;
    in_circle_in_circle_fcmp_32ns_32ns_1_1_1<1,1,32,32,1>* in_circle_fcmp_32ns_32ns_1_1_1_U19;
    sc_signal< sc_lv<13> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > grp_fu_84_p2;
    sc_signal< sc_lv<32> > reg_173;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > grp_fu_90_p2;
    sc_signal< sc_lv<32> > reg_183;
    sc_signal< sc_lv<32> > grp_fu_96_p2;
    sc_signal< sc_lv<32> > reg_192;
    sc_signal< sc_lv<32> > grp_fu_102_p2;
    sc_signal< sc_lv<32> > reg_201;
    sc_signal< sc_lv<32> > grp_fu_108_p2;
    sc_signal< sc_lv<32> > reg_210;
    sc_signal< sc_lv<32> > grp_fu_114_p2;
    sc_signal< sc_lv<32> > reg_219;
    sc_signal< sc_lv<32> > grp_fu_120_p2;
    sc_signal< sc_lv<32> > reg_228;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > grp_fu_124_p2;
    sc_signal< sc_lv<32> > reg_233;
    sc_signal< sc_lv<32> > grp_fu_128_p2;
    sc_signal< sc_lv<32> > reg_238;
    sc_signal< sc_lv<32> > grp_fu_132_p2;
    sc_signal< sc_lv<32> > tmp_3_reg_292;
    sc_signal< sc_lv<32> > grp_fu_136_p2;
    sc_signal< sc_lv<32> > tmp_4_reg_297;
    sc_signal< sc_lv<32> > grp_fu_140_p2;
    sc_signal< sc_lv<32> > tmp_5_reg_302;
    sc_signal< sc_lv<32> > grp_fu_144_p2;
    sc_signal< sc_lv<32> > tmp_6_reg_307;
    sc_signal< sc_lv<32> > grp_fu_148_p2;
    sc_signal< sc_lv<32> > tmp_7_reg_312;
    sc_signal< sc_lv<32> > grp_fu_152_p2;
    sc_signal< sc_lv<32> > tmp_8_reg_317;
    sc_signal< sc_lv<32> > grp_fu_156_p2;
    sc_signal< sc_lv<32> > tmp_9_reg_322;
    sc_signal< sc_lv<32> > grp_fu_160_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_327;
    sc_signal< sc_lv<32> > grp_fu_164_p2;
    sc_signal< sc_lv<32> > tmp_10_reg_332;
    sc_signal< sc_lv<32> > grp_fu_84_p0;
    sc_signal< sc_lv<32> > grp_fu_84_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<32> > grp_fu_90_p0;
    sc_signal< sc_lv<32> > grp_fu_90_p1;
    sc_signal< sc_lv<32> > grp_fu_96_p0;
    sc_signal< sc_lv<32> > grp_fu_96_p1;
    sc_signal< sc_lv<32> > grp_fu_102_p0;
    sc_signal< sc_lv<32> > grp_fu_102_p1;
    sc_signal< sc_lv<32> > grp_fu_108_p0;
    sc_signal< sc_lv<32> > grp_fu_108_p1;
    sc_signal< sc_lv<32> > grp_fu_114_p0;
    sc_signal< sc_lv<32> > grp_fu_114_p1;
    sc_signal< sc_lv<32> > grp_fu_120_p1;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > grp_fu_124_p0;
    sc_signal< sc_lv<32> > grp_fu_124_p1;
    sc_signal< sc_lv<32> > grp_fu_128_p0;
    sc_signal< sc_lv<32> > grp_fu_128_p1;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<1> > tmp_15_fu_168_p2;
    sc_signal< sc_lv<2> > grp_fu_84_opcode;
    sc_signal< sc_lv<2> > grp_fu_90_opcode;
    sc_signal< sc_lv<2> > grp_fu_96_opcode;
    sc_signal< sc_lv<13> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<13> ap_ST_fsm_state1;
    static const sc_lv<13> ap_ST_fsm_state2;
    static const sc_lv<13> ap_ST_fsm_state3;
    static const sc_lv<13> ap_ST_fsm_state4;
    static const sc_lv<13> ap_ST_fsm_state5;
    static const sc_lv<13> ap_ST_fsm_state6;
    static const sc_lv<13> ap_ST_fsm_state7;
    static const sc_lv<13> ap_ST_fsm_state8;
    static const sc_lv<13> ap_ST_fsm_state9;
    static const sc_lv<13> ap_ST_fsm_state10;
    static const sc_lv<13> ap_ST_fsm_state11;
    static const sc_lv<13> ap_ST_fsm_state12;
    static const sc_lv<13> ap_ST_fsm_state13;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_102_p0();
    void thread_grp_fu_102_p1();
    void thread_grp_fu_108_p0();
    void thread_grp_fu_108_p1();
    void thread_grp_fu_114_p0();
    void thread_grp_fu_114_p1();
    void thread_grp_fu_120_p1();
    void thread_grp_fu_124_p0();
    void thread_grp_fu_124_p1();
    void thread_grp_fu_128_p0();
    void thread_grp_fu_128_p1();
    void thread_grp_fu_84_opcode();
    void thread_grp_fu_84_p0();
    void thread_grp_fu_84_p1();
    void thread_grp_fu_90_opcode();
    void thread_grp_fu_90_p0();
    void thread_grp_fu_90_p1();
    void thread_grp_fu_96_opcode();
    void thread_grp_fu_96_p0();
    void thread_grp_fu_96_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
